routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});


Route::group(['middleware' => ['auth']], function () {
	Route::get('/home', 'HomeController@index')->name('home');

	Route::resources([
		'product_category' => 'ProductCategoryController',
		'product' => 'ProductController',
		'member_category' => 'MemberCategoryController',
		'members' => 'MemberController',
		'transactions' => 'TransactionController'
	]);
});

Auth::routes();

app/ProductCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductCategory extends Model
{
    //
}

app/Http/Controllers/ProductCategoryController.php
<?php

namespace App\Http\Controllers;

use App\ProductCategory;
use Illuminate\Http\Request;

class ProductCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = ProductCategory::all();
        return view('product_category.index', compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        return view('product_category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $category = new ProductCategory;
        $category->name = $request->name;
        $category->desc = $request->desc;
        $category->save();
        return redirect()->route('product_category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = ProductCategory::findOrFail($id);
        return view('product_category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = ProductCategory::findOrFail($id);
        $category->name = $request->name;
        $category->desc = $request->desc;
        $category->update();
        return redirect()->route('product_category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = ProductCategory::findOrFail($id);
        $category->delete();
        return redirect()->route('product_category.index');
    }
}

resources/views/product_category/create.blade.php
@extends('layouts.template')

@section('content')
<!-- Basic Validation -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Tambah Data Kategori</h2>
            </div>
            <div class="body">
                <form action="{{route('product_category.store')}}" method="POST">
                    @csrf
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" class="form-control" id="name" name="name" required>
                            <label class="form-label">Nama Kategori</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <textarea name="desc" id="desc" cols="30" rows="5" class="form-control no-resize" required></textarea>
                            <label class="form-label">Deskripsi Kategori</label>
                        </div>
                    </div>
                    <button class="btn btn-danger waves-effect" type="submit">SIMPAN</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- #END# Basic Validation -->
@endsection

resources/views/product_category/edit.blade.php
@extends('layouts.template')

@section('content')
<!-- Basic Validation -->
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Edit Data Kategori</h2>
            </div>
            <div class="body">
                <form action="{{route('product_category.update', $category->id)}}" method="POST">
                    @csrf
                    @method('put')
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" class="form-control" id="name" name="name" value="{{ $category->name }}">
                            <label class="form-label">Nama Kategori</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <textarea name="desc" id="desc" cols="30" rows="5" class="form-control no-resize">{{ $category->desc }}</textarea>
                            <label class="form-label">Deskripsi Kategori</label>
                        </div>
                    </div>
                    <button class="btn btn-danger waves-effect" type="submit">SIMPAN</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- #END# Basic Validation -->
@endsection

resources/views/product_category/index.blade.php
@extends('layouts.template')

@section('content')
<div class="container-fluid">
    <!-- Basic Examples -->
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        DATA KATEGORI PRODUK
                    </h2>
                    <ul class="header-dropdown m-r--5">
                        <li>
                            <a href="{{route('product_category.create')}}">
                                <button type="button" class="btn btn-default waves-effect btn-sm"><i class="material-icons">add_circle</i></button>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                            <thead>
                                <tr>
                                	<th>No</th>
                                    <th>Nama Kategori</th>
                                    <th>Deskripsi Kategori</th>
                                    <th>Pilihan</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>No</th>
                                    <th>Nama Kategori</th>
                                    <th>Deskripsi Kategori</th>
                                    <th>Pilihan</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @foreach($category as $i => $item)
                                <tr>
                                    <td>{{$i+1}}</td>
                                    <td>{{$item->name}}</td>
                                    <td>{{$item->desc}}</td>
                                    <td>
                                        <form action="{{ route('product_category.destroy',$item->id) }}" method="post">
                                            <a href="{{ route('product_category.edit',$item->id) }}">
                                                <button type="button" class="btn btn-success btn-sm"><i class="material-icons">edit</i></button>
                                            </a>
                                            @csrf 
                                            @method('delete')
                                                <button type="submit" class="btn btn-danger btn-sm" 
                                                onclick="return confirm('Yakin ingin dihapus ?')"><i class="material-icons">delete</i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Basic Examples -->
</div>
@endsection